import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

const products = [
  {
    name: 'Classic White Button-Down Shirt',
    description: 'A timeless white shirt perfect for any occasion',
    price: 45.99,
    imageUrl: '/placeholders/product-1.jpg',
    category: 'tops',
    colors: ['white'],
    styles: ['minimalist', 'formal', 'casual'],
    patterns: ['solid'],
    season: 'all',
    tags: ['basics', 'office', 'versatile'],
    purchaseLink: '#',
  },
  {
    name: 'High-Waist Straight Jeans',
    description: 'Classic straight-cut jeans with a high waist for a flattering silhouette',
    price: 89.99,
    imageUrl: '/placeholders/product-2.jpg',
    category: 'bottoms',
    colors: ['navy', 'black'],
    styles: ['casual', 'streetwear'],
    patterns: ['solid'],
    season: 'all',
    tags: ['denim', 'everyday', 'basics'],
    purchaseLink: '#',
  },
  {
    name: 'Flowy Bohemian Maxi Dress',
    description: 'Effortlessly chic maxi dress with floral print',
    price: 78.50,
    imageUrl: '/placeholders/product-3.jpg',
    category: 'dresses',
    colors: ['beige', 'blush'],
    styles: ['bohemian', 'romantic'],
    patterns: ['floral'],
    season: 'spring/summer',
    tags: ['boho', 'festival', 'vacation'],
    purchaseLink: '#',
  },
  {
    name: 'Oversized Blazer',
    description: 'Power dressing meets comfort in this oversized blazer',
    price: 129.99,
    imageUrl: '/placeholders/product-4.jpg',
    category: 'outerwear',
    colors: ['camel', 'black', 'gray'],
    styles: ['formal', 'minimalist', 'streetwear'],
    patterns: ['solid'],
    season: 'fall/winter',
    tags: ['office', 'power dressing', 'layering'],
    purchaseLink: '#',
  },
  {
    name: 'Ribbed Knit Turtleneck',
    description: 'Cozy ribbed turtleneck for cooler days',
    price: 52.00,
    imageUrl: '/placeholders/product-5.jpg',
    category: 'tops',
    colors: ['camel', 'white', 'black', 'gray'],
    styles: ['minimalist', 'casual'],
    patterns: ['solid'],
    season: 'fall/winter',
    tags: ['cozy', 'basics', 'layering'],
    purchaseLink: '#',
  },
  {
    name: 'Pleated Midi Skirt',
    description: 'Elegant pleated midi skirt for effortless style',
    price: 65.00,
    imageUrl: '/placeholders/product-6.jpg',
    category: 'bottoms',
    colors: ['blush', 'emerald', 'mustard'],
    styles: ['romantic', 'minimalist', 'formal'],
    patterns: ['solid'],
    season: 'all',
    tags: ['feminine', 'elegant', 'versatile'],
    purchaseLink: '#',
  },
  {
    name: 'Graphic Streetwear Tee',
    description: 'Bold graphic tee for an edgy streetwear look',
    price: 35.99,
    imageUrl: '/placeholders/product-7.jpg',
    category: 'tops',
    colors: ['black', 'white'],
    styles: ['streetwear', 'casual'],
    patterns: ['graphic'],
    season: 'all',
    tags: ['urban', 'edgy', 'statement'],
    purchaseLink: '#',
  },
  {
    name: 'Linen Wide-Leg Trousers',
    description: 'Breathable linen trousers with a relaxed wide-leg fit',
    price: 72.50,
    imageUrl: '/placeholders/product-8.jpg',
    category: 'bottoms',
    colors: ['beige', 'white', 'navy'],
    styles: ['minimalist', 'bohemian', 'casual'],
    patterns: ['solid'],
    season: 'spring/summer',
    tags: ['linen', 'relaxed', 'vacation'],
    purchaseLink: '#',
  },
  {
    name: 'Leather Crossbody Bag',
    description: 'Compact leather crossbody bag for everyday use',
    price: 155.00,
    imageUrl: '/placeholders/product-9.jpg',
    category: 'accessories',
    colors: ['camel', 'black', 'white'],
    styles: ['minimalist', 'casual', 'formal'],
    patterns: ['solid'],
    season: 'all',
    tags: ['bag', 'accessory', 'everyday'],
    purchaseLink: '#',
  },
  {
    name: 'Floral Wrap Dress',
    description: 'Flattering wrap dress with a gorgeous floral print',
    price: 88.00,
    imageUrl: '/placeholders/product-10.jpg',
    category: 'dresses',
    colors: ['blush', 'emerald'],
    styles: ['romantic', 'bohemian', 'casual'],
    patterns: ['floral'],
    season: 'spring/summer',
    tags: ['floral', 'feminine', 'date night'],
    purchaseLink: '#',
  },
  {
    name: 'Classic Denim Jacket',
    description: 'Iconic denim jacket, a wardrobe essential',
    price: 95.00,
    imageUrl: '/placeholders/product-11.jpg',
    category: 'outerwear',
    colors: ['navy'],
    styles: ['casual', 'streetwear', 'bohemian'],
    patterns: ['solid'],
    season: 'spring/fall',
    tags: ['denim', 'layering', 'classic'],
    purchaseLink: '#',
  },
  {
    name: 'Strappy Heeled Sandals',
    description: 'Elegant strappy sandals for a polished look',
    price: 115.00,
    imageUrl: '/placeholders/product-12.jpg',
    category: 'shoes',
    colors: ['beige', 'black', 'white'],
    styles: ['formal', 'romantic', 'minimalist'],
    patterns: ['solid'],
    season: 'spring/summer',
    tags: ['heels', 'elegant', 'date night'],
    purchaseLink: '#',
  },
  {
    name: 'Cropped Puffer Jacket',
    description: 'Trendy cropped puffer jacket for winter warmth with style',
    price: 148.00,
    imageUrl: '/placeholders/product-13.jpg',
    category: 'outerwear',
    colors: ['black', 'navy', 'blush'],
    styles: ['streetwear', 'casual'],
    patterns: ['solid'],
    season: 'fall/winter',
    tags: ['winter', 'warm', 'trendy'],
    purchaseLink: '#',
  },
  {
    name: 'Slip Satin Dress',
    description: 'Luxurious satin slip dress for evening occasions',
    price: 125.00,
    imageUrl: '/placeholders/product-14.jpg',
    category: 'dresses',
    colors: ['blush', 'black', 'emerald'],
    styles: ['romantic', 'formal', 'minimalist'],
    patterns: ['solid'],
    season: 'all',
    tags: ['evening', 'luxe', 'elegant'],
    purchaseLink: '#',
  },
  {
    name: 'Chunky Knit Cardigan',
    description: 'Oversized chunky knit cardigan for a cozy aesthetic',
    price: 98.00,
    imageUrl: '/placeholders/product-15.jpg',
    category: 'tops',
    colors: ['camel', 'gray', 'white'],
    styles: ['casual', 'bohemian', 'minimalist'],
    patterns: ['solid'],
    season: 'fall/winter',
    tags: ['cozy', 'knit', 'oversized'],
    purchaseLink: '#',
  },
  {
    name: 'Plaid Wool Coat',
    description: 'Classic plaid wool coat for timeless winter style',
    price: 245.00,
    imageUrl: '/placeholders/product-16.jpg',
    category: 'outerwear',
    colors: ['camel', 'black', 'gray'],
    styles: ['formal', 'minimalist', 'casual'],
    patterns: ['plaid'],
    season: 'fall/winter',
    tags: ['wool', 'winter', 'classic'],
    purchaseLink: '#',
  },
  {
    name: 'Striped Breton Top',
    description: 'Nautical-inspired striped top, a French wardrobe staple',
    price: 42.00,
    imageUrl: '/placeholders/product-17.jpg',
    category: 'tops',
    colors: ['navy', 'white'],
    styles: ['casual', 'minimalist'],
    patterns: ['striped'],
    season: 'all',
    tags: ['nautical', 'french', 'classic'],
    purchaseLink: '#',
  },
  {
    name: 'Velvet Mini Skirt',
    description: 'Rich velvet mini skirt for a bold evening look',
    price: 68.00,
    imageUrl: '/placeholders/product-18.jpg',
    category: 'bottoms',
    colors: ['emerald', 'black', 'mustard'],
    styles: ['romantic', 'streetwear', 'formal'],
    patterns: ['solid'],
    season: 'fall/winter',
    tags: ['velvet', 'evening', 'bold'],
    purchaseLink: '#',
  },
  {
    name: 'Canvas Sneakers',
    description: 'Classic canvas sneakers for effortless casual style',
    price: 65.00,
    imageUrl: '/placeholders/product-19.jpg',
    category: 'shoes',
    colors: ['white', 'black', 'navy'],
    styles: ['casual', 'streetwear', 'sporty'],
    patterns: ['solid'],
    season: 'all',
    tags: ['sneakers', 'casual', 'everyday'],
    purchaseLink: '#',
  },
  {
    name: 'Silk Scarf',
    description: 'Versatile silk scarf to elevate any outfit',
    price: 55.00,
    imageUrl: '/placeholders/product-20.jpg',
    category: 'accessories',
    colors: ['blush', 'mustard', 'emerald'],
    styles: ['minimalist', 'bohemian', 'romantic'],
    patterns: ['floral', 'geometric'],
    season: 'all',
    tags: ['accessory', 'silk', 'versatile'],
    purchaseLink: '#',
  },
  {
    name: 'Cargo Wide-Leg Pants',
    description: 'Utilitarian-chic cargo pants with wide leg cut',
    price: 85.00,
    imageUrl: '/placeholders/product-21.jpg',
    category: 'bottoms',
    colors: ['camel', 'black', 'gray'],
    styles: ['streetwear', 'casual'],
    patterns: ['solid'],
    season: 'all',
    tags: ['utility', 'trendy', 'comfortable'],
    purchaseLink: '#',
  },
  {
    name: 'Embroidered Boho Blouse',
    description: 'Delicate embroidery details on a flowing bohemian blouse',
    price: 58.00,
    imageUrl: '/placeholders/product-22.jpg',
    category: 'tops',
    colors: ['white', 'beige'],
    styles: ['bohemian', 'romantic', 'casual'],
    patterns: ['floral', 'geometric'],
    season: 'spring/summer',
    tags: ['boho', 'embroidery', 'feminine'],
    purchaseLink: '#',
  },
]

async function main() {
  console.log('Seeding products...')
  for (const product of products) {
    await prisma.product.create({
      data: {
        ...product,
        colors: JSON.stringify(product.colors),
        styles: JSON.stringify(product.styles),
        patterns: JSON.stringify(product.patterns),
        tags: JSON.stringify(product.tags),
      },
    })
  }
  console.log('Seeding complete!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
